### ISSUE TITLE
Problem of distinguish some OpenTiles

### ISSUE THREAD

**Issue by Typas** [h1g0/mahjong_rs#30]
There's some problem I cannot understand from your `opened.rs`

1. How do you distinguish which tile is taken from other in `Chi` type?

2. How do you distinguish 小明槓（ショウミンカン） and 大明槓（ダイミンカン）?

**Comment by h1g0** [comment]
@Typas 

> How do you distinguish which tile is taken from other in `Chi` type?

Set the following to [`OpenType.from`](https://github.com/h1g0/mahjong_rs/blob/96470b047da34d1103a630a8f4b061978dcf6c8d/src/hand_info/opened.rs#L37):

- Used when `Chi`, `Pon`, or `Kan` has occurred: 
  - [`OpenFrom::Previous`](https://github.com/h1g0/mahjong_rs/blob/96470b047da34d1103a630a8f4b061978dcf6c8d/src/hand_info/opened.rs#L18): 上家
  - [`OpenFrom::Following`](https://github.com/h1g0/mahjong_rs/blob/96470b047da34d1103a630a8f4b061978dcf6c8d/src/hand_info/opened.rs#L22): 下家
  - [`OpenFrom::Opposite`](https://github.com/h1g0/mahjong_rs/blob/96470b047da34d1103a630a8f4b061978dcf6c8d/src/hand_info/opened.rs#L24): 対面
- Used only when `Kan` has occurred: 
  - [`OpenFrom::Myself`](https://github.com/h1g0/mahjong_rs/blob/96470b047da34d1103a630a8f4b061978dcf6c8d/src/hand_info/opened.rs#L20): 自家

>How do you distinguish 小明槓（ショウミンカン） and 大明槓（ダイミンカン）?

This distinction is currently not yet implemented.

**Comment by h1g0** [comment]
Since this issue has been inactive for some time, I will close it. If you need to re-open it again, please feel free to do so.
